# 第二次课作业

（1）创建一个1到10的数组，然后逆序输出。

In [3]:
import numpy as np
a1=np.arange(1,10)
print(a1[::-1])


[9 8 7 6 5 4 3 2 1]


（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [ ]:
a2=np.ones(20)
a2=a2.reshape(4,5)
a2=a2.T
print(a2)
print(a2.shape)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


: 

: 

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [ ]:
a3=np.random.rand(3,3,3)
print(a3)

[[[0.11763894 0.36394471 0.67653095]
  [0.35973983 0.69812815 0.14803089]
  [0.16934838 0.18251735 0.17546874]]

 [[0.11142272 0.44405975 0.78954035]
  [0.48288836 0.42179532 0.47037603]
  [0.65923652 0.66550525 0.4255492 ]]

 [[0.6247673  0.7691689  0.9694261 ]
  [0.87391602 0.21541655 0.22840196]
  [0.1009916  0.08286921 0.59735577]]]


: 

: 

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [ ]:
a4=np.random.randint(1,10,10)
print(a4)
a4=np.sort(a4)
print(a4)
order=np.argsort(a4)
print(order)
print(f"min value:{a4[order[0]]}")
print(f"sum:{a4.sum()}")
print(f"var:{a4.var()}")

[4 7 1 6 5 6 9 9 6 2]
[1 2 4 5 6 6 6 7 9 9]
[0 1 2 3 4 5 6 7 8 9]
min value:1
sum:55
var:6.25


: 

: 

（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [ ]:
a5=np.random.randint(1,10,10)
print(a5)
a5[a5%2==1]

[9 2 1 7 6 9 8 5 8 9]


array([9, 1, 7, 9, 5, 9])

: 

: 

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [ ]:
a6=np.arange(0,101,5.0)
print(a6)
print(a6.dtype)
# a6.astype(np.int32)
np.asarray(16,dtype=np.int32)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]
float64


array(16, dtype=int32)

: 

: 

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [5]:
a7 = np.random.uniform(1,10,10)
print(a7)
print(a7.dtype)
a7[(a7>3)&(a7<8)]*=-1
a7


[2.88425909 1.72004913 8.26304566 1.94526595 8.2029402  6.54647543
 8.49411949 4.82716495 7.87121785 9.48611318]
float64


array([ 2.88425909,  1.72004913,  8.26304566,  1.94526595,  8.2029402 ,
       -6.54647543,  8.49411949, -4.82716495, -7.87121785,  9.48611318])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [4]:
a8=[1,2,3,4,5]
temp=np.zeros

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [9]:
a9=np.random.rand(5,5)
print(a9)
a9[[0,1]]=a9[[1,0]]
print(a9)

[[0.4559014  0.20950032 0.50744527 0.80776993 0.88678358]
 [0.58305017 0.771182   0.3622474  0.0621176  0.56421447]
 [0.85356959 0.3397486  0.03083069 0.93502043 0.76598842]
 [0.88596045 0.2486767  0.88038661 0.14215587 0.3791427 ]
 [0.67075894 0.89561377 0.0467771  0.02902895 0.57797084]]
[[0.58305017 0.771182   0.3622474  0.0621176  0.56421447]
 [0.4559014  0.20950032 0.50744527 0.80776993 0.88678358]
 [0.85356959 0.3397486  0.03083069 0.93502043 0.76598842]
 [0.88596045 0.2486767  0.88038661 0.14215587 0.3791427 ]
 [0.67075894 0.89561377 0.0467771  0.02902895 0.57797084]]


（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

In [15]:
a10=np.random.rand(10,2)
x=a10[:,0]
y=a10[:,1]

r=np.sqrt(x**2+y**2)
theta=np.arctan2(y,x)

# polar_a10=np.dstack((r,theta))
polar_a10=np.column_stack((r,theta))
print(polar_a10)


[[0.05173327 0.9041989 ]
 [1.04502368 0.32865452]
 [1.08137053 1.0013072 ]
 [0.80516573 1.40015155]
 [0.68414523 0.49475263]
 [0.4419109  1.53452545]
 [0.45945406 1.56565116]
 [0.44572525 1.13936611]
 [0.49321218 0.23204267]
 [0.88891286 0.42915842]]


（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [16]:
a11=np.ones(10)*2
a11[4]=1

（12）创建一个长度为10的随机向量，并求其累计和。

In [18]:
a12=np.random.rand(10)
print(a12)
a12.sum()

[0.25030745 0.12290526 0.95961475 0.14820575 0.14445752 0.70862209
 0.46856329 0.36032752 0.72446424 0.24528018]


np.float64(4.132748040188783)

（13）将数组中的所有奇数替换成-1。

In [19]:
a13=np.random.randint(0,10,10)
print(a13)
a13[a13%2==1]=-1
print(a13)

[2 4 8 6 8 5 2 9 8 5]
[ 2  4  8  6  8 -1  2 -1  8 -1]


（14）构造两个2乘3的二维数组，按照3种方法进行连接？

In [23]:
a141=np.ones((2,3))
a142=np.ones((2,3))*2
a14=np.concatenate((a141,a142),axis=1)
print(a14)
a14=np.concatenate((a141,a142),axis=0)
print(a14)
a14=np.vstack((a141,a142))
print(a14)
a14=np.hstack((a141,a142))
print(a14)
a14=np.dstack((a141,a142))
print(a14)


[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]
[[[1. 2.]
  [1. 2.]
  [1. 2.]]

 [[1. 2.]
  [1. 2.]
  [1. 2.]]]


（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
aidx=np.where(a==b)
print("aidx:",aidx)
print(a[aidx])


aidx: (array([1, 3, 5, 7]),)
[2 2 4 4]


（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [27]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
idx=np.where((a>5)&(a<10))
print("idx:",idx)
print(a[idx])


idx: (array([0, 4, 6, 8, 9]),)
[7 7 9 9 8]
